name: Request a feature
description: Create a feature request to suggest an idea or enhancement
title: "Feature request: "
labels: enhancement
body:
- type: markdown
  attributes:
    value: Thank you for taking the time to request a feature. Community contributions like yours are key to the development and adoption of XMTP.
- type: textarea
  id: problem-description
  attributes:
    label: Is your feature request related to a problem?
    description: Provide a clear and concise description of the problem to be solved.
- type: textarea
  id: solution
  attributes:
    label: Describe the solution to the problem
    description: Provide a clear and concise description of what you want to happen to solve the problem.
- type: textarea
  id: details
  attributes:
    label: Additional details
    description: Add any other details about your feature request. Attach screenshots, if applicable.
