name: Feature Request
description: Create a feature request to suggest an idea or enhancement. Community contributions like yours are key to the development and adoption of XMTP.
title: "[Feature request]: "
labels: enhancement
body:
- type: textarea
  id: problem-description
  attributes:
    label: Is your feature request related to a problem?
    description: Provide a clear and concise description of the problem to be solved.
  validations:
    required: false
- type: textarea
  id: solution
  attributes:
    label: Describe the solution to the problem
    description: Provide a clear and concise description of what you want to happen to solve the problem.
  validations:
    required: true
- type: textarea
  id: details
  attributes:
    label: Additional details
    description: Add any other details about your feature request. Attach screenshots, if applicable.
  validations:
    required: false
